# .pre-commit-config.yaml
default_install_hook_types: [pre-commit, pre-push, commit-msg]
minimum_pre_commit_version: "3.6.0"

repos:
  - repo: https://github.com/psf/black
    rev: 24.8.0
    hooks: 
      - id: black
        exclude: ^(pylk-old/|old-rag-code/|src-old/)

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.6.9
    hooks:
      - id: ruff
        args: ["--fix"]
        exclude: ^(pylk-old/|old-rag-code/|src-old/)

  # Removing mypy, because it caused problems
  # - repo: local
  #   hooks:
  #     - id: mypy
  #       name: mypy
  #       entry: tools/pre-commit/mypy.sh
  #       language: system
  #       types: [python]
  #       exclude: ^(pylk-old/|old-rag-code/|src-old/)

  # detect-secrets disabled due to setuptools compatibility issues
  # - repo: https://github.com/Yelp/detect-secrets
  #   rev: v1.5.0
  #   hooks:
  #     - id: detect-secrets
  #       args: ["--baseline", ".secrets.baseline"]
  #       stages: [pre-commit]

  - repo: local
    hooks:
      - id: enforce-milestone-size
        name: Enforce milestone size (warn ≥300, fail >500 LOC)
        language: system
        entry: tools/pre-commit/enforce-milestone-size.sh
        stages: [pre-commit]

      - id: lint-no-pint-in-widgets
        name: No PINT imports in widgets
        language: system
        entry: tools/pre-commit/lint-no-pint-in-widgets.sh
        stages: [pre-commit]

  - repo: https://github.com/commitizen-tools/commitizen
    rev: v3.27.0
    hooks:
      - id: commitizen
        stages: [commit-msg]
